require 'rubygems'
require 'hoe'
require 'pp'

Hoe.add_include_dirs('server')

Hoe.spec 'Zonk' do |p|
  p.developer('Ned Konz', 'ned-ruby@bike-nomad.com')
  p.dependency('sinatra', '~>1.3')
  p.license('MIT')
  p.rubyforge_name='bikeNomad'
  p.spec_extras = {
    :rdoc_options => lambda { |o| o.concat(%w[-f hanna]) },
    :require_paths => %w[lib server test]
  }
  p.testlib = :minitest
  # pp p.spec unless p.spec.nil?
end

desc 'make tags for vim'
task :tags do
  sh('ctags -R lib test')
end

desc 'run a simple task'
task :simple do
  ruby('-Ilib:test', 'examples/simple_task.rb')
end

desc 'make coverage report'
task :simplecov do
  tests = ['rubygems', 'minitest/autorun']
  tests.concat(Dir.glob("test/**/*.rb"))
  tests.map! { |f| %(require "#{f}") }
  sh "ruby -w -I.:lib:test -e 'require \"rubygems\"; require \"simplecov\"'" +
    " -e 'SimpleCov.command_name \"test:lib\"; SimpleCov.add_filter \"/test/\"; SimpleCov.start'" +
    " -e 'require \"minitest/autorun\"'" +
    " -e '#{tests.join("; ")}'"

end

# vim: syntax=ruby
