require 'rubygems'
require 'hoe'
require 'pp'

Hoe.add_include_dirs('server')

Hoe.spec 'Zonk' do |p|
  p.developer('Ned Konz', 'ned-ruby@bike-nomad.com')
  p.dependency('sinatra', '~>1.3')
  p.dependency('simplecov', '~>0.7', :dev)
  p.license('MIT')
  p.rubyforge_name='bikeNomad'
  p.spec_extras = {
    :rdoc_options => lambda { |o| o.concat(%w[-f hanna]) },
    :require_paths => %w[lib server test]
  }
  p.testlib = :minitest
  p.clean_globs = %w(lib/zonk/grammar.rb examples/simple_task.rb)
end

desc 'test zonk compiler'
task :compiler_test => [ 'lib/zonk/grammar.rb', 'examples/simple_task.rb' ] do
  ruby('-Ilib', 'examples/simple_task.rb')
end

# Compile a Treetop .tt file into a Ruby file
rule '.rb' => [ '.tt' ] do |t|
  sh "tt -o #{t.name} #{t.source}"
end

# Compile a Zonk .zonk file into a Ruby file
rule '.rb' => [ '.zonk' ] do |t|
  args = %w(-Ilib bin/zonkc -o) << t.name << t.source
  ruby(*args)
end

desc 'make tags for vim'
task :tags do
  sh 'ctags -R lib test'
end

desc 'run a simple task'
task :simple do
  ruby('-Ilib:test', 'examples/simple_task_ruby.rb')
end

desc 'make coverage report'
task :simplecov do
  tests = ['rubygems', 'minitest/autorun']
  tests.concat(Dir.glob("test/**/*.rb"))
  tests.map! { |f| %(require "#{f}") }
  sh "ruby -w -I.:lib:test -e 'require \"rubygems\"; require \"simplecov\"'" +
    " -e 'SimpleCov.command_name \"test:lib\"; SimpleCov.add_filter \"/test/\"; SimpleCov.start'" +
    " -e 'require \"minitest/autorun\"'" +
    " -e '#{tests.join("; ")}'"
end

# vim: syntax=ruby
